.github/workflows/android.yml
- close #23 
- github actions에 kakao native app key를 secrets로 세팅해 ci 빌드 시 값을 가져올 수 있도록 구현
=> :construction_worker: #23 ci 빌드를 위한 secrets 세팅

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/mashup/gabbangzip/sharedalbum/MainApplication.kt, data/build.gradle.kts, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/base/PicResponse.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/datasource/LocalDataSourceImpl.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/di/DataSourceModule.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/di/NetworkModule.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/di/RepositoryModule.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/request/LoginRequest.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/LoginResponse.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/interceptor/AuthInterceptor.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/LoginRepositoryImpl.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/service/LoginService.kt, domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/datasource/LocalDataSource.kt, domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/model/LoginParam.kt, domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/repository/LoginRepository.kt, domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/usecase/LoginUseCase.kt, gradle.properties, gradle/libs.versions.toml, presentation/build.gradle.kts, presentation/src/main/AndroidManifest.xml, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/auth/KakaoUserSdkUtil.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/login/LoginViewModel.kt, settings.gradle.kts
- close #17 
- UI 작업 XXXX
- 카카오 로그인 SDK 설정 
- local.properties 에 kakao_native_app_key 설정이랑 키해시 등록 필요해!!
- 네트워크 모듈 설정
- 카카오 로그인 성공 시, 닉네임, 프로필 이미지와 함께 서비스 서버 로그인 (현재는 임시 서버)
- Encrypted Shared Preferences 기본 셋팅 및 토큰 저장
- [API 스펙](https://www.notion.so/4df39fcc912a4ce8a687a6b0a96cb958)
[고민되는 부분](https://www.notion.so/f281aefc54024923a71720628c940952?pvs=4)이 있는데 이거 계속 고민하다가는 개발 안 끝날 것 같아서 일단 올렸어 같이 고민해주라..
=> [#17] 카카오 로그인, 로컬 저장소 구현

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/theme/Color.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/theme/Theme.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicSnackbar.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/model/PicSnackbarType.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/login/LoginActivity.kt, presentation/src/main/res/drawable/ic_check.xml, presentation/src/main/res/drawable/ic_warning.xml
- close #33
- 스낵바 컴포넌트 구현
- 로그인 실패 시 스낵바 출력
- 스낵바가 생각보다 화면에서 사용하기가 너무 불편하더라고..? Scaffold도 써야하고 메시지 외에 부가적인 데이터를 넘기는 방법이 안 보여서 actionLabel은 이렇게 쓰라고 있는게 아닌 것 같지만 actionLabel에 type.name 찾아서 아이콘 설정하게끔 구현해두었엉
- 마침 임시서버가 닫혀서 테스트하기 좋더라..?
[Screen_recording_20240626_000911.webm](https://github.com/mash-up-kr/gabbangzip-Android/assets/78132126/3adcb6b8-b7ec-416f-ba1d-6b4d7911a40c)
=> [#33] 스낵바 컴포넌트 구현, 로그인 실패 시 스낵바 출력

data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/di/NetworkModule.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/di/qualifier/NetworkQualifier.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/request/TokenRefreshRequest.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/TokenRefreshResponse.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/interceptor/TokenAuthenticator.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/LoginRepositoryImpl.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/service/LoginService.kt, domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/base/PicException.kt, domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/repository/LoginRepository.kt
- close #45 
- 401 에러 발생 시 토큰 리프레시 후 재요청
- 리프레시 실패 시 LoginRequiredException
- 무한 루프 방지를 위해 토큰 리프레시 필요 여부에 따라 주입하는 네트워크 객체 분리
=> [#45] 토큰 리프레시

data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/base/PicResponse.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/GroupRepositoryImpl.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/LoginRepositoryImpl.kt
- close #86 
- PicResponse에서 data 만 꺼내주는 메서드를 하나 만들었는데 별 내용 없어유,, ㅎ
- 원래는 에러 핸들러를 만들어볼까 하다가 정우오빠가 전에 했던 말처럼 우리가 커스텀 에러코드를 받긴하지만 당장 사용할 필요는 없어보여서 그냥 성공하면 data만 꺼내주고, 실패하면 예외 던지게끔만 해놨슴다. null 처리는 귀찮으니까.
=> [#86] API 호출 간소화

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicDatePickerField.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicGallery.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicTextField.kt, presentation/src/main/res/drawable/ic_calender.xml, presentation/src/main/res/drawable/ic_gallery.xml, presentation/src/main/res/values/strings.xml
- close #80
- close #81 
- 갤러리 컴포넌트 및 날짜 선택 필드 구현
=> [#80][#81] 갤러리 컴포넌트 및 날짜 선택 필드 구현

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/utils/ModifierExt.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/utils/MultipleEventsCutterManager.kt
- close #93 
- 더블클릭 방지 코드 추가 및 적용
- Flow 의 debounce 기능을 이용해서 적용한 케이스가 있던데 이 코드를 그대로 적용해보는 것은 어떨까싶어 가져와보았어요~
- https://al-e-shevelev.medium.com/how-to-prevent-multiple-clicks-in-android-jetpack-compose-8e62224c9c5e
=> [#93] 더블클릭 방지 코드 추가 및 적용

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/GroupCreationActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/GroupCreationViewModel.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/complete/GroupCreationCompleteScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/complete/navigation/GroupCreationCompleteNavigation.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/navigation/GroupCreationNavHost.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/navigation/GroupCreationRoute.kt, presentation/src/main/res/values/strings.xml
- close #11 
- 그룹 완료하면 UI 디자인 구현
- 링크복사 없어질 수 있는데 추후에 변경되면 따로 이슈 올릴 예정이에요~!
- 그룹 만들기 화면은 Activity 에서 UiState 를 가지고 있는 구조이다보니 Snackbar 노출하는 기능을 별도의 SharedFlow 로 빼주었습니다. 
=> 부연설명 : 다른 화면처럼 state 에 snackbarMessage 같은걸 추가해서 구현하는 방법도 있었지만, 이게 클릭하면 clipboard 에 복붙하고 snackbar 보여줘야하는 로직이라.. 클릭할 때 마다 snackbar 가 노출되게 하려면 버튼 클릭할 때 마다 `uiState.copy(snackbarMessage = null)` `uiState.copy(snackbarMessage = "링크를 복사했어요.")` 로 구현해야하는데, 이건 비효율적인 것 같아서 별도의 SharedFlow 로 신호 받아서 처리하도록 구현했습니다)
- https://www.figma.com/design/kZd5C2Mgr2NHKYvefeztSu/Design-file?node-id=1480-6987&t=tQWusB3nrfi58l1P-4
https://github.com/user-attachments/assets/f9ad453c-45ac-492f-bd5b-12ca35181c16
=> [#11] 그룹 완료화면 UI 디자인 구현

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicPhotoCard.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/utils/StableImage.kt
- close #117 
- PicPhotoCard 안에 이미지가 아닌 화면이 들어가는 케이스가 있어서.. 이거를 편하게 할 수 있도록 작업하게 되었습니다
- PicPhotoCard 을 좀 더 재사용하기 쉬우면서도 기존코드에 영향가지 않도록 리팩토링 하는 것이 목적입니다
이렇게 사진이 들어갈 때도 있지만
이렇게 사진이 아닌 화면이 들어갈 때도 있다.
=> [#117] PicPhotoCard 확장성 개선

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicPhotoCard.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailRecentEvent.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailScreen.kt
- close #108 
- 포토카드 없이 크롭된 이미지가 필요해서 PicCroppedPhoto 컴포저블 추가했습니당
- 그룹상세 프레임 적용
- 그룹상세 배경색 Gray0 적용
=> [#108] 그룹상세 프레임 적용

data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/CreateGroupResponse.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/GroupRepositoryImpl.kt, domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/model/group/GroupInfoDomainModel.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/GroupCreationViewModel.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/complete/GroupCreationCompleteScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/complete/model/GroupCreationResult.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/splash/SplashActivity.kt, presentation/src/main/res/values/strings.xml
- close #122 
- 그룹생성 초대코드 대응
- 그룹 초대링크가 아닌 초대코드로 받도록 수정했습니다
- https://www.figma.com/design/kZd5C2Mgr2NHKYvefeztSu/Design-file?node-id=1480-6987&t=ovRz52H9U45DVLTM-4
=> [#122] 그룹생성 초대코드 복사하기 추가

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/FlippableBox.kt
- close #138 
- 카드 플립할때 영역 넘어가지 않도록 조정했습니당~
- 계원이가 워낙 잘 구현해줘서 간단하게 해결됐습니다 ㅋㄷㅋㄷ 지렸다리.
https://github.com/user-attachments/assets/054039fc-efe7-4212-92c9-29005c4c721d
=> [#138] 그룹 홈 화면 Card 플립 효과 개선

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- close #175 
- build 오류 수정 (GroupHomeScreen 인자전달 변경)
=> [#175] GroupHomeScreen 인자 전달이 연결되지 않아 생긴 빌드오류 수정

data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/service/GroupService.kt
- close #181 
- 그룹 관련 api id -> groupId로 이름 변경했습니다~
=> [#181] 그룹 관련 api path인자 수정

data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/group/GroupDetailResponse.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/group/HistoryResponse.kt, domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/model/group/HistoryDomainModel.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicTopBar.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailHistory.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/HistoryDetailScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/model/HistoryItem.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/preview/EventHistoryProvider.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/model/GroupInfo.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/utils/LocalDateUtil.kt
- close #171 
- close #155 
- 우리들의 인생네컷 썸네일 컴포저블 구현
- history 맵핑 로직 추가
- LocalDateTime -> String format util 정의
- 그룹상세 이미지뷰어 스크린 구현
- 다크모드 탑바 추가
- 그룹상세에서 이미지뷰어 연결까지 하고 싶었는데 음.. 네비게이션이나 인텐트로 객체를 넘기는게 좀 오래걸릴 것 같아서 화면 연결은 다른 이슈로 처리하겠읍니다
<br />
=> [#171][#155] 그룹상세 우리들의 인생네컷 프레임, 이미지뷰어 스크린

data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/common/Constants.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/common/S3Ext.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/group/CardBackImageResponse.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/group/GroupDetailResponse.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/group/GroupResponse.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/GroupRepositoryImpl.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailRecentEvent.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailViewModel.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/model/GroupEvent.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/utils/LocalDateUtil.kt
- close #189 
- 데이터 형식 UI 요구사항에 맞게 수정 완료입니당
- 서버에서 주는 이미지 URL이 앞에 url 을 추가해야 하는 번거로움이 있는데 확장함수로 하나 빼서 그룹상세, 그룹조회 적용 완료입니당
<br />
=> [#189] 그룹 상세 데이터 맵핑

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/splash/SplashScreen.kt
- close #187 
- 스플래시 화면 디자인 적용
- https://www.figma.com/design/kZd5C2Mgr2NHKYvefeztSu/Design-file?node-id=1641-6843&t=Yyi9wb9QjddZPaUQ-4
https://github.com/user-attachments/assets/26ad0915-8155-4878-a375-7189f3387fba
=> [#187] 스플래시 화면 디자인 적용

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- close #196 
- 역대 이벤트, 진행 중 이벤트 모두 없는 경우
- 그룹상세 이동 제한
- 네비게이션 아이콘 숨김
- 수정하는 김에 그룹 키워드 태그 UI 요구사항에 맞게 데이터 맵핑
=> [#196] 역대 이벤트, 진행 중 이벤트 모두 없을 때 그룹상세 이동 제한

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicPhotoCard.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailRecentEvent.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailViewModel.kt, presentation/src/main/res/values/strings.xml
- close #172 
- 그룹상세 네컷사진이 만들어졌어요 프레임 적용
- NO_CURRENT_EVENT, EVENT_COMPLETE 일 때 공유 기능 활성화
- 좀만 더하면 포토카드 일반화가 가능할지도?
=> [#172] 그룹상세 네컷사진이 만들어졌어요 프레임

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/complete/navigation/GroupCreationCompleteNavigation.kt
- close #210 
- 그룹 생성 완료화면에서 뒤로가기 누르면 이전 UI 잠깐 뜸
https://github.com/user-attachments/assets/24a4b8b7-0f19-4271-9e19-e60e2201b694
-> 이제 뒤로가기 하면 "완료" 버튼을 누른것과 동일하게 동작한다.
=> [#210] 완료화면으로 넘어갈 때 backStack 모두 제거

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailScreen.kt
- close #204 
- 바텀시트 최소 높이보다 좀 더 크게 패딩 먹이고 스크롤 가능하게끔 수정했습니당
https://github.com/user-attachments/assets/0c0b9927-3c32-4f23-b2ee-fbaaeceb1496
=> [#204] 그룹상세 스크롤 가능하도록 수정

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/model/GroupDetailUiState.kt
- close #218 
- 그룹상세 진행중 이벤트 없을때 이벤트 생성 가능하도록 수정
=> [#218] 그룹상세 진행중 이벤트 없을때 이벤트 생성 가능하도록 수정

presentation/src/main/AndroidManifest.xml, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/theme/Theme.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/GroupCreationActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/invitation/InvitationCodeActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/login/LoginActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/MainActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/HistoryDetailActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/HistoryDetailState.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/model/HistoryItem.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/navigation/GroupDetailNavigation.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/model/CardBackImage.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/navigation/MainNavHost.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/splash/SplashActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/VoteActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/utils/ImmutableList.kt
- close #199 
- close #221 
- 어우 Serializable로 겨우 해냈구요.. 하는김에 statusbar 색상이 눈에 밟혀서 쪼금씩 수정했어유
<br/>
<br/>
=> [#199][#221] 그룹상세 이미지뷰어 연결

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- close #228 
- 이벤트 인자에다가 값을 안넣었더라구요 ㅎ 넣어서 해결했습니다~
=> [#228] 그룹 생성시 이벤트명 안뜨는 버그 

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/FlippableBox.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- close #229 
- 뒷면에 사진 없으면 플립되지 않도록 수정
=> [#229] enableFlip 추가 및 뒷면 카드 없으면 뒤집지 않도록 추가

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/common/GroupCreationScaffold.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/complete/GroupCreationCompleteScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/intro/GroupCreationIntroScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/keyword/GroupCreationKeywordScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/name/GroupCreationNameScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/thumbnail/GroupCreationThumbnailScreen.kt
- close #159 
- 그룹 생성하기 완료 화면 내 링크 복사 버튼 잘림
- 기타 화면들도 이런 상황에서 스크롤 될 수 있도록 처리 작업 진행
- 그룹 생성관련 화면들 공통로직 GroupCreationScaffold 로 정리 후 적용
https://github.com/user-attachments/assets/7f135aad-0b0b-4205-97d2-5394dddec1b6
참고) 디바이스의 최소 width 를 조정해서 스크롤 상황이 발생할 수 있도록 강제하여 테스트했습니당
=> [#159] 그룹 생성하기 완료 화면 내 링크 복사 버튼 잘림

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/splash/SplashActivity.kt
- close #252 
- checkPermission 로직이 true,false일때 로직 순서가 바껴서 권한 요청이 안뜬거 였습니다..ㅎ 수정 했어욜~
=> [#252] 앱 진입시 권한 요청 안하는 버그 

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeViewModel.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/model/CardBackImage.kt
- close #263 
- 4개만 받아오도록 코드 수정했습니다~~
- 4개 이하면 뭔가 부분적으로 보여주는거 보다 empty로 반환해서 그냥 카드 플립안되게 하는게 나을거 같고 안보여주는게 나을거 같다는 생각에 4개이면 empty로 반환하게 했습니다.. 다른 방법이 낫다고 하면 코멘트 주세용~
=> [#263] 인생네컷 사진 받아올때 4개까지만 받아오도록 방어 코드 추가

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/login/LoginActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/login/LoginViewModel.kt
- close #242 
- 카카오앱 깔려있을 때 카카오로 로그인 되도록 수정
- applicationContext 를 카카오 로그인의 context 로 넣어주면 카카오로그인시 오류가 발생한다. (NEW_TASK 가 불가능한 context 라고 오류가 뜸) 그래서 Activity Context 가 제공되도록 변경하였다.
https://github.com/user-attachments/assets/a21f347a-6ee8-4bf4-b6a4-95787490371e
https://github.com/user-attachments/assets/04f957d0-7927-448b-8308-ffdd0b1dca49
=> [#242] 카카오앱 깔려있을 때 카카오로 로그인 되도록 수정

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicLoadingIndicator.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationState.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationViewModel.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/detail/EventCreationDetailScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/GroupCreationUiState.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/GroupCreationViewModel.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/thumbnail/GroupCreationThumbnailScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/MainActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/MainViewModel.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeViewModel.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/model/CardBackImage.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/model/MainEvent.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/model/MainUiState.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/PhotoVoteScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/VoteViewModel.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/model/PhotoVoteState.kt
- close #264 
- close #268 
- 로딩화면 구현 완료했습니다~~ 뭔가 그냥 단색 프로그레스바로 로딩도는게 안이뻐서 저희 키워드 색깔로 구현했습니다. 별로면 말해주기..ㅎ
- 픽 고르고 사진 선택해서 업로드, 그룹 홈으로 진입, 그룹만들기, 이벤트 만들기, 투표 시작전, 투표 완료 할때 로딩 추가 했습니다. 다른 것도 있다면 말해 주십셔.
- 진짜 대박 사건인게 인생네컷 방어하기 코드도 map을 안넣고 toUiModel하는 바람의 재귀가 돌아서 무한루프가 돌더라구요..ㅎ 수정했습니다 같이...
**[로딩 인디케이터]**
https://github.com/user-attachments/assets/d16dc871-a4a1-4c89-a870-3b854baeae1e
**[그룹 홈 진입 로딩 ]**
https://github.com/user-attachments/assets/aac1900d-d894-4c17-8a74-b0261dd5a848
**[그룹 만들기 로딩]**
https://github.com/user-attachments/assets/73ad907f-0956-48bc-9f03-0e74552a7be3
**[픽고르기 로딩]**
https://github.com/user-attachments/assets/671ae8c7-e461-41f5-ba6a-3f7782b37ed3
- 위 동영상과 같은 느낌입니다.. ㅎ 빠진게 있는데 못찍었습니다,,,,ㅎ
=> [#264][#268] 로딩 인디케이터 추가

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomePhotoCard.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- close #201 
- 홈 포토카드 뒷면 이미지 짤림 방지
- contentMaxHeight 가 기기의 절반사이즈이다. 그래서 기기에 따라 뒷면 이미지가 한번에 표현되지 못할 수 있다.
=> contentMaxHeight 제거, LazyVerticalGrid 가 적용된 BackImage 에만 기기의 높이만큼 max height 값을 주었음 (어차피 이 값을 넘을 수 없음) 이렇게하면 FrontImage 와 BackImage 를 모두 가변높이로 잡아줄 수 있음
- BackImage 는 1:1 비율이지만, FrontImage 는 1:1 비율이 아니어서, 두 화면의 높이가 상이한 문제점 발생
=> FrontImage 에 aspectRatio 를 통해 1:1 비율로 제공하도록 수정
**Before**
https://github.com/user-attachments/assets/573758dc-9198-419c-9770-d9b4a9afb776
**After**
https://github.com/user-attachments/assets/225ceb22-a853-4cda-aab2-a969d726c4ab
=> [#201] 홈 포토카드 뒷면 이미지 짤림 방지

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationState.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationViewModel.kt, presentation/src/main/res/values/strings.xml
- close #246 
- 이벤트 생성하기, 4개 이미지 업로드 시 하나씩 업로드도 가능하도록 개선
- 4개 이상 선택되면 경고메시지가 뜨면서 나머지 이미지들은 등록되지 않게 구현완료
https://github.com/user-attachments/assets/c9ed5626-c2d3-4825-a700-216c4b97d248
=> [#246] 이미지 하나씩 업로드 할 수 있도록 수정

domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/usecase/UploadImageListUseCase.kt, domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/usecase/UploadMyPicUseCase.kt, domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/usecase/event/CreateEventUseCase.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/MainActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/utils/FileUtil.kt
- close #247
- jpeg 압축 및 변환, async 이용해서 업로드 속도 단축했습니당
- 코루틴을 맞게 사용되어있는지는 사실 아직 아리까리 하네용..? 보통 내픽올리기나 이벤트 만들때 사진 가져올 시, 메인 스레드에서 실행 되지만 파일 압축,변환 작업은 Dispathcer.IO로 백그라운드 작업하는 거를 의도했는데 아니라면 코멘트 부탁드립니당..
- 성능 비교는 아래 링크 참조해 주세용~~
- https://www.notion.so/7bf969c4c1f741679ad5bac848dc4465?pvs=4
- https://s2choco.tistory.com/18
=> [#247] 내픽올리기 / 이벤트만들기 등 속도 개선

data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/group/GroupWithdrawResponse.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/GroupRepositoryImpl.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/service/GroupService.kt, domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/model/group/WithdrawalGroupDomainModel.kt, domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/repository/GroupRepository.kt, domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/usecase/group/WithdrawGroupUseCase.kt
- close #295 
- 그룹 나가기 API 구현
- http://ec2-43-203-14-157.ap-northeast-2.compute.amazonaws.com/swagger-ui/index.html#/%EA%B7%B8%EB%A3%B9/withdrawGroup
=> [#295] 그룹 나가기 API 구현

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/VoteActivity.kt
- close #297 
- 조건문 추가해서 수정 완료 했슴다~~
https://github.com/user-attachments/assets/20409b73-29db-4553-aacf-b6096bd01ff4
=> [#297] 투표화면 에러 토스트 발생하는 버그 

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- close #299 
- 플로팅 버튼 클릭 시 나오는 배경화면 수정
- https://www.figma.com/design/kZd5C2Mgr2NHKYvefeztSu/Design-file?node-id=4406-28092&t=sgwgdAyGEsSUQsfy-4
Before | After
:--: | :--:
=> [#299] 플로팅 버튼 클릭 시 나오는 배경화면 수정

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicPhotoCard.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- close #281 
- 이미지 placeholder 적용
- 인생네컷이랑, 한장짜리 있는 곳도 Placeholder 적용 안된곳 적용시키기
- 흰색으로 넣어주는 것으로 협의 완료
Before | After
:--: | :--:
https://github.com/user-attachments/assets/d105dd87-f83b-498e-9adf-55a731ae6f33
=> [#281] 모든 단일/네컷 사진에 placeholder 추가

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailScreen.kt
- close #305 
- GroupDetail 화면 들어가보면 TopBar 와 네컷사진 사이 공간이 너무 많은 것 같음. (실제로 비교해보면 조금 다름)
- background 강제로 주고 확인해보니 실제로 BottomSheetScaffold 의 topBar 에 넣어주면 content 사이에 의도하지 않은 공간이 생기는 것을 확인하였음
Before | After
:--: | :--:
=> [#305] BottomSheetScaffold 를 사용할 때 실 디자인과 실제 앱이 다르게 나오는 점 수정

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/complete/GroupCreationCompleteScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/thumbnail/GroupCreationThumbnailScreen.kt
- close #307 
- 그룹썸네일 화면, 그룹생성완료 화면에 placeholder 추가
Before | After
:--: | :--:
https://github.com/user-attachments/assets/916ae4a6-441b-45e6-b64a-beb535b4f714
=> [#307] 그룹썸네일 화면, 그룹생성완료 화면에 placeholder 추가

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicTag.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/common/ThumbnailCardFrame.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- close #302 
- PicTag 공통화 로직으로 다시 모으기
- PicTag 에 늘어나봐야 그렇게 인자가 많이 안늘어날 것 같아서, 같이 가져가는 식으로 다시 모아주었습니다
- 확실히 사용처에서는 중복코드가 사라져서 깔끔해지긴 한 것 같긴한데, 더 좋은 아이디어가 보인다면 마음편히 의견 부탁드립니다~
=> [#302] PicTag 공통로직으로 다시 모아주기

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/GroupCreationActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/navigation/GroupCreationNavHost.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/MainActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/navigation/MainNavHost.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/utils/NavControllerExt.kt
- close #312 
- Compose Navigation Stack 비워졌을 때 Activity 종료하도록 코드 추가
- 타이밍 맞춰서 뒤로가기 두번 누르면 아무리 debounce 를 걸어두었더라도 두번 클릭이 적용된다 (ㅠㅠ)
https://github.com/user-attachments/assets/c0fcd561-9cc8-4954-ac49-dfda39445e8e
**Before**
<br>
<br>
https://github.com/user-attachments/assets/9220fe18-e509-4e1d-9ca6-9745ad002aaf
**After**
=> [#312] Compose Navigation Stack 비워졌을 때 Activity 종료하도록 코드 추가

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeViewModel.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/model/FilterTag.kt
- close #308 
- 그룹이 없을때는 태그가 보여지지 않도록 구현
Before | After
:--: | :--:
https://github.com/user-attachments/assets/193eacda-f31a-4be3-a18f-3f8275617766
=> [#308] 현재 존재하는 태그들만 노출되도록 수정

data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/base/PicApiErrorParser.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/base/PicResponse.kt, data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/GroupRepositoryImpl.kt, domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/base/PicException.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/invitation/InvitationCodeActivity.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/invitation/InvitationCodeUiState.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/invitation/InvitationCodeViewModel.kt, presentation/src/main/res/values/strings.xml
- close #287 
- PicApiErrorParser 구현
- 서비스에서 정의한 에러 발생 시 PicApiException 형태로 파싱해서 던지고 그외는 그대로 던집니당
- 로그 라인별 설명
1.   API 에러 발생 시 응답 (`PicResponse<T>`)
2.   파싱 결과 (`PicErrorResponse`)
3.   API 에러 (존재하지 않는 코드)
4.   그외 에러 (와이파이 끄고 실행)
=> [#287] 그룹원이 다 찬 방에 들어갔을 때, 다 찼다고 에러 명시

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/complete/GroupCreationCompleteScreen.kt, presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/GroupMemberScreen.kt, presentation/src/main/res/values/strings.xml
- close #328 
- 초대코드 복사 클릭 시 "링크를 복사했어요." 가 아니라 "코드를 복사했어요." 로 변경
- "초대코드 복사" => "코드 복사" 로 변경 필요
Before | After
:--: | :--:
=> [#328] 초대코드 복사 문구 변경

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/login/LoginScreen.kt
- close #326 
- 로그인 로띠 크기 수정
Figma
Before | After
:--: | :--:
=> [#326] 로그인화면 로띠가 너무 커요

presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/detail/EventCreationDetailScreen.kt
- close #334 
- 로딩 인디케이터 background 색상 설정
https://github.com/user-attachments/assets/b00b3018-e3db-420f-b5a3-d7408c5e568f
=> [#334] 이벤트 생성 화면에 로딩 인디케이터 겹침
