- README.md
- close #2 
- Readme 에 코드컨벤션 관련 정리 링크 추가
- https://github.com/mash-up-kr/gabbangzip-Android/wiki/Code-Convention
> [#2] Readme 에 코드컨벤션 관련 정리 링크 추가

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/theme/Color.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/theme/Theme.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/theme/Typography.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicKeywordButton.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicTag.kt
- presentation/src/main/res/values/strings.xml
- close #21 
- Tag 및 KeywordButton 컴포넌트 제작
- color 및 typography 변경 사항 적용
- 버튼이랑 같이 올리려다가 이거 먼저 올린당
> [#21] Tag 및 KeywordButton 컴포넌트 제작

- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/di/NetworkModule.kt
> [#41] 임시서버 변경된 주소로 수정

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/utils/PicPhotoPicker.kt
- close #40 
- 사용법
```kotlin
private val photoPicker = PicPhotoPicker.create(
activity = this,
max = 2, // 여러개 필요할 때만
onImagePicked = { /*TODO*/ },
)
```
```kotlin
onClick = {
photoPicker.open()
},
```
> [#40] 포토 피커 유틸 구현

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/theme/Color.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicButton.kt
- presentation/src/main/res/values/strings.xml
- close #22 
- button 컴포넌트 제작 
- 사용법은 preview 참고하기~
- alpha color 정의
> [#22] button 컴포넌트 제작 

- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/base/PicResponse.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/request/LoginRequest.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/LoginResponse.kt
- close #48 
- 프로퍼티 명 camel case -> snake case 변경 대응
> [#48] snake case 로 변경

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicTextField.kt
- close #44 
- TextField 컴포넌트 제작
실 기기로 보면 밑줄 안 보임.
[Screen_recording_20240629_202523.webm](https://github.com/mash-up-kr/gabbangzip-Android/assets/51108983/8804c3f3-b4d0-4b83-8834-af4a7f62ca0b)
> [#44] TextField 컴포넌트 제작

- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/LoginRepositoryImpl.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/repository/LoginRepository.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/usecase/CheckUserLoggedInUseCase.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/splash/SplashActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/splash/SplashUiState.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/splash/SplashViewModel.kt
- close #46 
- 스플래시에서 액세스 토큰 여부로 자동 로그인 들어갑니다~
> [#46] 자동 로그인

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicButton.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicDialog.kt
> [#52] Dialog 컴포넌트 제작

- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/di/NetworkModule.kt
> :bug: TokenAuthenticator 받도록 수정

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/GroupMemberProvider.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/GroupMemberScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/GroupMemberUiState.kt
- close #84 
- 이름이 변경되지 않은 부분들 마저 변경
> [#84] 빌드에러 수정 - 이름이 변경되지 않은 부분들 마저 변경

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/FlippableBox.kt
- close #90 
- FlippableBox 만들기
- 추후를 위해 드래그했을 때 움직이는것도 개발해봤어요
https://github.com/mash-up-kr/gabbangzip-Android/assets/18674395/0b2c0a7b-82af-4c41-928d-3cb85bcfd6d3
**Sample Code**
```
FlippableBox(
modifier = Modifier
.padding(top = 100.dp)
.size(200.dp, 300.dp),
frontScreen = {
Text(
modifier = Modifier
.matchParentSize()
.align(Alignment.Center)
.background(Color.LightGray),
text = "앞면입니다",
)
},
backScreen = {
Text(
modifier = Modifier
.matchParentSize()
.align(Alignment.Center)
.background(Color.Gray),
text = "뒷면입니다",
)
},
flipAnimationSpec = tween(
durationMillis = 700,
easing = LinearOutSlowInEasing,
),
enableFlipByDrag = true,
)
```
> [#90] FlippableBox 만들기

- .github/workflows/android.yml
- close #103 
- ci 워크플로우 수정 했습니다..
> [#103] FCM 위한 google-service secret생성 및 ci 수정 

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/mashup/gabbangzip/sharedalbum/service/PicMessagingService.kt
- app/src/main/java/com/mashup/gabbangzip/sharedalbum/utils/NotificationUtil.kt
- gradle/libs.versions.toml
- close #69 
- 백쪽에서 noti로만 준다 그래서 data는 빼놨습니다~
- 푸시는 첨해봐서 뭔가 달랐다면 코멘트 부탁 드립니다..
https://github.com/mash-up-kr/gabbangzip-Android/assets/59912150/45dcfa1e-aa12-46ea-9198-b7bf74ae2c9a
> [#69] 푸시알림 위한 fcm 구현

- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/common/Constants.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/CreateGroupResponse.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/GroupRepositoryImpl.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/service/AwsService.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/theme/Color.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicTag.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/GroupCreationActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/GroupCreationState.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/GroupCreationUiState.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/GroupCreationViewModel.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/common/ThumbnailCardFrame.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/complete/GroupCreationCompleteScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/complete/model/GroupCreated.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/complete/model/GroupCreationResult.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/complete/navigation/GroupCreationCompleteNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/navigation/GroupCreationNavHost.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/thumbnail/GroupCreationThumbnailScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/thumbnail/navigation/GroupCreationThumbnailNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/model/GroupKeyword.kt
- close #110 
- 그룹만들기 프레임 적용하기
- https://www.figma.com/design/kZd5C2Mgr2NHKYvefeztSu/Design-file?node-id=1480-6544&t=oroUWR5Si9XX2SkO-4
https://github.com/user-attachments/assets/10501630-21c4-40f3-a834-955a7d4e0114
**+) 참고 : 이미지가 잘 내려오지 않고 있어서.. 일단 임시로 response 에 imageURL 값 하드코딩해서 영상찍었음**
> [#110] 그룹 만들기 프레임 적용

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/VoteCompleteScreen.kt
- presentation/src/main/res/values/strings.xml
> [#13] 투표완료 화면 UI

- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/usecase/invitation/EnterGroupByInvitationCodeUseCase.kt
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/keyword/GroupCreationKeywordScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/name/GroupCreationNameScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/thumbnail/GroupCreationThumbnailScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/invitation/InvitationCodeActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/invitation/InvitationCodeScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/invitation/InvitationCodeUiState.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/invitation/InvitationCodeViewModel.kt
- presentation/src/main/res/values/strings.xml
- close #120
- 초대코드 입력화면 UI
- 이게 진입점이 여러곳이라서 액티비티로 따로 뺐습니다~
- 유스케이스, 뷰모델, state 연결해놨으니 API 나오면 유스케이스만 수정하면 될듯~
> [#120] 초대코드 입력 화면 UI

- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/FileRepositoryImpl.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/service/AwsService.kt
- close #130 
- presigned URL Content-Type 추가
- 미사용 값 제거 (AwsService.BASE_URL)
> [#130] presigned URL Content-Type 추가

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/theme/Theme.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/detail/EventCreationDetailScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/intro/EventCreationIntroScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/GroupCreationActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/keyword/GroupCreationKeywordScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/name/GroupCreationNameScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/invitation/InvitationCodeScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/login/LoginScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/MainActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailRecentEvent.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/mypage/MyPageScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/VoteCompleteScreen.kt
- close #143 
- 디폴트 백그라운드 색상이 좀 푸르딩딩한 색으로 보여서 Gray0 매번 넣기는 불편하니까 테마로 설정했습니당
- dynamicColor를 허용하게 되면 또 Material 내부적으로 정의한 팔레트 쓰길래 껐습니다₩
> [#143] 디폴트 백그라운드 색상 설정

- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/request/FcmTokenRequest.kt
- close #147 
- 다른거 확인하려고 인스펙터를 켰다가 아래처럼 에러가 나서 보니까
- 리퀘스트에 이름을 안 붙여서 보내서 에러가 나는 것 같더라구요
- value class -> data class 수정했더니 잘 되던데 혹시 다른 방법 아시는분
> [#147] FCM 토큰 등록 실패 이슈 수정

- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/request/EnterGroupRequest.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/group/EnterGroupResponse.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/GroupRepositoryImpl.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/service/GroupService.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/repository/GroupRepository.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/usecase/invitation/EnterGroupByInvitationCodeUseCase.kt
- close #140 
- 그룹 들어가기 API 연동
> [#140] 그룹 들어가기 API 연동

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/GroupCreationActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/invitation/InvitationCodeActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/MainActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/navigation/MainNavHost.kt
- close #142 
- 플로팅 버튼 메뉴 네비게이션 로직 연동
- 고민되는 부분이 좀 있는데 MainNavHost에 람다가 너무 많아지는 것 같아서 navController가 필요하지 않은 이동은 위로 끌어올릴 필요없이 가장 하위에서 LocalContext 받아서 이동시켜도 되지 않을까 하는 생각이 드는데 어뗘..?
> [#142] 플로팅 버튼 메뉴 네비게이션 로직 연동

- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/MainActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailRecentEvent.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/navigation/GroupDetailNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/navigation/MainNavHost.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/utils/CaptureBitmapUtil.kt
- presentation/src/main/res/xml/filepaths.xml
- close #156 
- Composable -> Bitmap 변환 유틸 구현
- Bitmap -> 이미지화 -> 다른 앱으로 공유
- 다른 이슈인데 이벤트가 종료됐을 때 툴바 클릭 이벤트 TODO로 되어 있는게 보이길래 이벤트 생성화면 연결해뒀습ㄴㅣ다
- 근데 완성된 네컷사진이 아직 Box로 들어가 있어서 수정해야 함.. 
- 아래 영상은 로그인 버튼 클릭하면 로그인 버튼 컴포저블 공유하는 테스트
https://github.com/user-attachments/assets/304f55c7-bebf-48e8-9b6b-ca8a75161331
> [#156] 완성된 네컷사진 공유하기

- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/di/NetworkModule.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/di/RepositoryModule.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/request/CreateEventRequest.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/CreateEventResponse.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/EventRepositoryImpl.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/service/EventService.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/model/eventcreation/EventCreationDomainModel.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/model/eventcreation/EventCreationParam.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/repository/EventRepository.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/usecase/CreateEventUseCase.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/usecase/UploadImageUseCase.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationState.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationViewModel.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomePhotoCard.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/navigation/GroupHomeNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/navigation/MainNavHost.kt
- close #65 
- 이벤트 생성하기 API 연결
- 이벤트 생성할 때는 사진 4개를 업로드해야해서.. 요 로직 어떻게 생각하시는지 함 봐주시면 감사하겠슴다
> [#65] 이벤트 생성하기 API 연결

- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/group/GroupMemberResponse.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/GroupRepositoryImpl.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/service/GroupService.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/model/group/MemberDomainModel.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/repository/GroupRepository.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/usecase/group/GetGroupMembersUseCase.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/MainActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/navigation/GroupDetailNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/GroupMemberProvider.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/GroupMemberScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/GroupMemberUiState.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/GroupMemberViewModel.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/model/Member.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/navigation/GroupMemberNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/navigation/MainNavHost.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/navigation/MainRoute.kt
- presentation/src/main/res/values/strings.xml
> [#154] 그룹원 목록 API 연동

- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/vote/VotePhotoOptionResponse.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/vote/VotePhotoResponse.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/VoteRepositoryImpl.kt
- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/service/VoteService.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/model/vote/VotePhotoDomainModel.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/repository/VoteRepository.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/usecase/vote/GetVotePhotoListUseCase.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/MainActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailViewModel.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/model/GroupDetailUiState.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/navigation/GroupDetailNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/navigation/GroupHomeNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/navigation/MainNavHost.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/PhotoCard.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/PhotoVoteScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/VoteActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/VoteViewModel.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/model/Photo.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/model/PhotoVoteState.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/model/VotePhoto.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/navigation/VoteNavHost.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/navigation/VoteNavigation.kt
- close #150 
- 구현 완료했슴다~ 전 이슈에서 이벤트 아이디가 필요없는 줄 알았는데 api 보니깐 필요하더라구요..ㅎ eventId 인자 추가했습니단
- 에러 메시지가 정해져서 error : String? 이게 필요없어진거 같아서 isError로 바꿨습니다. 혹시 아니라면 코멘트 남겨주세효..
> [#150] 투표할 이미지 가져오는 api 구현

- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/service/GroupService.kt
> [#183] 그룹 들어가기 GET -> POST

- presentation/src/main/res/values/strings.xml
> [#192] 우리들의 인생네컷 empty 문구 변경

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomePhotoCard.kt
- close #203 
- 이벤트 종료된 상태인데 이벤트 생성하기 버튼 안 뜸 이슈 수정
> [#203] 이벤트 종료된 상태인데 이벤트 생성하기 버튼 안 뜸

- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/vote/VotePhotoOptionResponse.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/VoteViewModel.kt
- close #205 
- url 문제였습니다.. 지혜가 만든 확장함수 추가했습니다~
> [#205] 투표 화면 내 이미지 안 뜸

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationState.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationViewModel.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/MainActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/MainViewModel.kt
- close #173 
- 이벤트 생성하기 완료 후 그룹 상세 화면으로 천이되도록 세팅
https://github.com/user-attachments/assets/03d61fde-1da0-4eb5-b343-1def9fc5b308
> [#173] 이벤트 생성하기 완료 후 그룹 상세 화면으로 천이되도록 세팅

- app/src/main/res/values/strings.xml
- close #215 
- 앱 이름 교체
Before | After
:--: | :--:
> [#215] 앱 이름 교체

- presentation/src/main/res/values/strings.xml
> [#214] 앱스토어 링크 교체

- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/dto/response/vote/VoteResultResponse.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/VoteActivity.kt
- close #225 
- toS3url적용, 테마 적용으로 해결했습니다~~
> [#225] 투표 완료후 투표 완료 스크린 오류

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/contract/Contract.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeViewModel.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/PhotoCard.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/PhotoVoteScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/VoteViewModel.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/model/VoteClickInfo.kt
- close #223 
- close #227 
- clickInfo가 변경될 때 실행되는 launchedEffect조건 수정하고 인덱스로 판별하는 로직 수정해서 고쳤습니다..
- 버튼 실시간으로 안바뀌는거는 WhileSubscribed 인자 삭제해서 했습니다~
- 뭔가 더 리팩토링이 가능은 할 거 같은데 일단 동작이 잘 됩니다,..ㅎ
- 영상은 못 찍었지만 잘 됩니단..
> [#223] 투표 완료후 좋아요한 이미지 업데이트 안되는 버그

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/splash/SplashActivity.kt
- close #230 
- 권한 물어보는 로직 추가했습니다~~ 권한 선택 한 이후 checkLogin 로직 돌아가도록 코드 작성했어열~
> [#230] 알림 권한 허용하도록 물어보는 기능 추가하기

- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/usecase/group/GetGroupDetailUseCase.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailViewModel.kt
- close #234 
- 그룹상세 재진입 시 리프레시!
> [#234] 그룹상세 재진입 시 리프레시

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/detail/EventCreationDetailScreen.kt
- close #232 
- 이벤트 만들기 측면 살짝 짤리는 이슈
> [#232] 이벤트 만들기 측면 살짝 짤리는 이슈

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- close #239 
- 홈 화면 topbar에 top padding 추가
- 상단에 넘 붙어있는 거 같아서..ㅎㅎ
> [#239] 홈 화면 topbar에 top padding 추가

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- close #244 
- FloatingActionButton 클릭하면 닫히도록 수정
https://github.com/user-attachments/assets/bfd9a9ba-cff1-404b-a136-00b528404f81
> [#244] FloatingActionButton 클릭하면 닫히도록 수정

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeViewModel.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/model/GroupHomeUiState.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/navigation/GroupHomeNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/navigation/MainNavHost.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/utils/ImmutableList.kt
- presentation/src/main/res/values/strings.xml
- close #256 
- GroupHomeScreen 에서 네트워크 연결 실패 시 예외처리
https://github.com/user-attachments/assets/c27f4151-4c1f-4b14-8bd7-d7c20410f676
> [#256] GroupHomeScreen 에서 네트워크 연결 실패 시 예외처리

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicButton.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailRecentEvent.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomePhotoCard.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/utils/ModifierExt.kt
- close #255 
- 버튼 햅틱 구현 완료 했습니다~~~
- 보니깐 디바운스가 이미 계원이가 잘 적용해놨더라구요..ㅎ 왜 적용안된줄 알았지,,ㅎ_ㅎ 그래서 햅틱반응만 추가했습니다~
> [#255] 쿡찌르기 버튼 햅틱 기능 추가

- README.md
- close #274 
- 리드미 작성 완료했습니당~~
- 프리뷰로 볼수 있음 좋을거 같은뎅 뭔가 구성이 별로시면 말해주세여~~
> [#274] 리드미 추가

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/theme/Color.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicSnackbar.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/thumbnail/GroupCreationThumbnailScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/MainActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/navigation/GroupDetailNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/navigation/GroupHomeNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/GroupMemberScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/navigation/GroupMemberNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/mypage/MyPageScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/mypage/navigation/MyPageNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/navigation/MainNavHost.kt
- close #282 
- 그룹 홈 플로팅버튼 바탕 클릭 시 닫기기능 + 쉐도우 처리
- https://www.figma.com/design/kZd5C2Mgr2NHKYvefeztSu/Design-file?node-id=372-1638&t=9r4NNjDTDRreTctC-4
https://github.com/user-attachments/assets/773b8563-5b39-4a5b-badb-dbce22cb7d88
> [#282] 그룹 홈 플로팅버튼 바탕 클릭 시 닫기기능 및 쉐도우처리

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupdetail/GroupDetailScreen.kt
- close #292 
- 중복 TopBar 코드 제거
Before | After
:--: | :--:
> [#292] 중복 TopBar 코드 제거

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/groupcreation/intro/GroupCreationIntroScreen.kt
- presentation/src/main/res/values/strings.xml
- close #314 
- 네명 그룹 만들기로 버튼 text 수정
> [#314] 네명 그룹 만들기로 버튼 text 수정

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicDatePickerDialog.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/common/PicDatePickerField.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationActivity.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationState.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationViewModel.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/detail/EventCreationDetailScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/detail/navigation/EventCreaetionDetailNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/navigation/EventCreationNavHost.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/utils/LocalDateUtil.kt
- presentation/src/main/res/values/strings.xml
- close #283 
- DatePickerDialog 구현
- 영상에서는 에러 스낵바가 떴는데 이벤트 생성은 200 떴슴당
```
2024-09-19 23:25:27.044 18280-28981 okhttp.OkHttpClient     com.mashup.gabbangzip.sharedalbum    I  {"group_id":114,"date":"2024-09-26T09:00","pictures":["pic/7cc46c27-d65f-4640-af39-c326a5559ab9.jpeg","pic/0d22f2d3-58c9-4f97-9ecf-5deb64c50429.jpeg","pic/126439d3-a612-4743-bd71-9aa1d9d47cc5.jpeg","pic/b1d12877-2e10-4400-bfca-64034bbca653.jpeg"],"description":"f"}
2024-09-19 23:25:27.044 18280-28981 okhttp.OkHttpClient     com.mashup.gabbangzip.sharedalbum    I  --> END POST (265-byte body)
2024-09-19 23:25:27.118 18280-28981 okhttp.OkHttpClient     com.mashup.gabbangzip.sharedalbum    I  <-- 200 http://ec2-43-203-14-157.ap-northeast-2.compute.amazonaws.com/api/v1/events (73ms)
``` …
> [#283] 이벤트 날짜 선택 기능 추가

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/GroupHomeScreen.kt
- presentation/src/main/res/values/strings.xml
- close #288 
- 홈화면 내 픽 올리기 최대 4장 명시
> [#288] 홈화면 내 픽 올리기 최대 4장 명시

- presentation/src/main/res/values/strings.xml
- close #301 
- 더 수정될 거 같은데 일단 올리기. 쿠쿸
> [#301] "이벤트" -> "네컷" 수정

- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/vote/PhotoVoteScreen.kt
- close #317 
- 투표 안내창 화면 변경 대응
- https://www.figma.com/design/kZd5C2Mgr2NHKYvefeztSu/Design-file?node-id=4406-21436&t=f5OmsgymFfaYZ31Y-4
https://github.com/user-attachments/assets/8383c2ef-bbac-4023-8780-f400d1782c28
> [#317] 투표 안내창 화면 변경 대응

- data/src/main/java/com/mashup/gabbangzip/sharedalbum/data/repository/GroupRepositoryImpl.kt
- domain/src/main/java/com/mashup/gabbangzip/sharedalbum/domain/base/PicException.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/EventCreationViewModel.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/eventcreation/detail/EventCreationDetailScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/grouphome/navigation/GroupHomeNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/GroupMemberScreen.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/GroupMemberUiState.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/GroupMemberViewModel.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/groupmember/navigation/GroupMemberNavigation.kt
- presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/ui/main/navigation/MainNavHost.kt
- presentation/src/main/res/values/strings.xml
- close #280 
- 그룹 나가기 기능 구현
- ~그룹 나가는 동작은 확인했으나 그룹 나갈 수 없을 때 스낵바 표시되는 동작은 확인 못해써요.. 지금 그룹 상세 진입이 안돼서 코드 먼저 올려요 진입되면 영상 올리겠숨다~
https://github.com/user-attachments/assets/c9e00009-ffbc-452a-aaac-aa6bcff707f6
그룹 한 개 있는 상태에서 그룹 탈퇴 시 그룹 생성 화면으로 이동
https://github.com/user-attachments/assets/de54b4f4-f153-467f-bd3a-62eb573bf344
> [#280] 그룹 나가기 기능
